version: '3.8'

services:
  sds-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sds-generator-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sds-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: sds-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sds-backend
    restart: unless-stopped
    networks:
      - sds-network
    profiles:
      - production

networks:
  sds-network:
    driver: bridge

volumes:
  sds-logs:
    driver: local
  sds-temp:
    driver: local